/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#2d1600",
        "outline-variant": "#3d494c",
        "secondary-container": "#3131c0",
        "on-secondary": "#1000a9",
        "on-tertiary-fixed-variant": "#6a3b00",
        "on-surface-variant": "#bcc9cd",
        "surface-container-high": "#2a2a2d",
        "inverse-surface": "#e4e1e6",
        "surface-container-highest": "#353438",
        "surface-container": "#1f1f22",
        "surface-tint": "#4cd7f6",
        tertiary: "#ffb873",
        "on-primary-fixed": "#001f26",
        "on-tertiary": "#4b2800",
        "surface-variant": "#353438",
        "on-tertiary-container": "#5b3200",
        "surface-bright": "#39393c",
        "surface-dim": "#131316",
        "tertiary-fixed-dim": "#ffb873",
        "surface-container-lowest": "#0e0e11",
        "primary-fixed-dim": "#4cd7f6",
        outline: "#869397",
        "primary-container": "#06b6d4",
        "on-error": "#690005",
        "on-secondary-container": "#b0b2ff",
        "error-container": "#93000a",
        "surface-container-low": "#1b1b1e",
        "on-primary-container": "#00424f",
        "secondary-fixed": "#e1e0ff",
        "inverse-primary": "#00687a",
        primary: "#4cd7f6",
        "on-background": "#e4e1e6",
        "inverse-on-surface": "#303033",
        error: "#ffb4ab",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed-variant": "#2f2ebe",
        surface: "#131316",
        "tertiary-container": "#e89337",
        "tertiary-fixed": "#ffdcbf",
        "on-surface": "#e4e1e6",
        "on-error-container": "#ffdad6",
        background: "#131316",
        "on-primary-fixed-variant": "#004e5c",
        "on-secondary-fixed": "#07006c",
        "on-primary": "#003640",
        "primary-fixed": "#acedff",
        secondary: "#c0c1ff",
      },
      borderRadius: {
        xs: "0.125rem",
        sm: "0.25rem",
        base: "0.5rem",
        lg: "0.75rem",
      },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        gutter: "24px",
      },
      fontFamily: {
        inter: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        code: ["13px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
